### ISSUE TITLE
Create CLI options

### ISSUE THREAD

**Issue by rajikaimal** [99xt/github-label-maker#1]
Options for
  - adding labels for all repos in an organization.
  - adding labels for specific repos in an organization.

**Comment by fdiogo** [comment]
This is taken care of on PR [#12](https://github.com/99xt/github-label-maker/pull/12)

**Comment by rajikaimal** [comment]
There's one issue we need to clarify, our initial goal was to apply labels to a repository at once, but I guess that functionality has broken now. @fdiogo

**Comment by fdiogo** [comment]
You mean several labels at once?

**Comment by rajikaimal** [comment]
For several repositories, just one label

**Comment by fdiogo** [comment]
Maybe I'm not getting it, but that is possible now. You can select an organization, any number of repositories and any number of issues and apply a label.

**Comment by rajikaimal** [comment]
Can we select all repos at once ?

**Comment by fdiogo** [comment]
Yes, when you select an organization it loads all the repos and presents them as a checklist. You can select all with "a" or one by one by hitting space. Then the same happens with the issues. The issues that are shown are all the issues combined of all the repositories selected previously.

**Comment by rajikaimal** [comment]
Great ! Then it fits our expectation.
